# [dein_lazy.toml]


# hook_add : deinによってプラグインが認識されたとき
# hook_source : プラグインを読み込む直前に
# hook_post_source : プラグインを読み込んだ直後


# on_i : インサートモードに入ったら読み込む
# on_ft : 特定のファイルタイプで読み込む
# on_func : 関数が事項されるときにロード
# on_event :  イベントが実行されるときにロード
# on_cmd : 

#################### エクスプローラー #################### 

# ファイルツリーを表示
[[plugins]]
repo = 'scrooloose/nerdtree'
depends = ['ryanoasis/vim-devicons']
on_event='NERDTreeToggle'
hook_add='''
nnoremap <silent> <Leader>e :NERDTreeToggle<CR>
'''

# file icon for filetree
[[plugins]]
repo = 'ryanoasis/vim-devicons'
on_source='nerdtree'

#################### 画面サイズ変更 #################### 

# ウィンドウの分割サイズを変更
[[plugins]]
repo = 'simeji/winresizer'
on_event='WinResizerStartResize'
hook_add='''
nnoremap <Leader>r :WinResizerStartResize<CR>
'''
#################### Quick Run #################### 

# vimを閉じずに編集中のファイルを素早く実行する
[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = '''
source ~/.cache/dein/repos/github.com/thinca/vim-quickrun/plugin/quickrun.vim
'''

# quick runに必要なライブラリ(非同期処理)
[[plugins]]
repo = 'Shougo/vimproc.vim'

#################### 言語ごとの設定 #################### 

# ---------- c++ ---------- 
[[plugins]]
repo = 'vim-scripts/DoxygenToolkit.vim'
on_ft = ['c', 'cpp']
hook_add = '''
nmap <leader>dox :Dox<CR>
'''

# ---------- Python ---------- 
[[plugins]]
repo = 'heavenshell/vim-pydocstring'
build='make install'
on_ft = ['python']
hook_add= '''
source ~/.cache/dein/repos/github.com/heavenshell/vim-pydocstring/ftplugin/python/pydocstring.vim
'''

# ---------- TOML ---------- 
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']


# ---------- WEB ---------- 

# カッコを自動で補完
[[plugins]]
repo = 'alvan/vim-closetag'
on_ft = ['js', 'html']
hook_add = '''
source ~/.cache/dein/repos/github.com/alvan/vim-closetag/plugin/closetag.vim
'''
